[package]
name = "reverse_shell"
version = "0.1.0"
authors = ["Your Name <your_email@example.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "reverse_shell"
path = "revshell.rs"
